### ISSUE TITLE
Bug: Typo made in description of script.

### ISSUE THREAD

**Issue by demeesterdev** [JelleGraaf/camelCase-to-PascalCase-converter#1]
# Description

When trying to run the script, I wasn't sure how to use it. 
As such I tried to `get-help` this script and I spotted something that must be a mistake or a typo.

# Steps to reproduce
```Powershell
PS \> (get-help .\Invoke-CaseConverter.ps1).description
```
# Expected Results
either:
```
This script converts all variables in a target script from camelCase to snake_case, the best style
```
or
```
This script converts all variables in a target script from camelCase to PascalCase, a mediocre style at best
```
# Actual results
when running the above command, I got:
```
This script converts all variables in a target script from camelCase to PascalCase, the best style
```

# Severity
This bug is very severe as it bothers me a lot. Please fix.

**Comment by Jawz84** [comment]
I experience this too, but in my opinion, it converts the wrong way! It should convert from any inferior casing system to camelCase, the best case scenario. 🐫❤️

**Comment by JasperCodes** [comment]
I agree with @demeesterdev, and additionally would like to see support added for kebab-case, `the-superior-style`

**Comment by demeesterdev** [comment]
@Jawz84 I do agree with the remark that it converts the wrong way. But on the topic of where to convert it to, as @JasperCodes points out, there are other cases to consider.

**Comment by Jawz84** [comment]
@demeesterdev I just noticed there is a small problem in your issue description: `snake-case` as mentioned by you, is actually formatted in kebab-case. Should have been `snake_case`.

We don't want to annoy the maintainer ofcourse.

**Comment by JelleGraaf** [comment]
I think we'll all have to agree to disagree. Case closed.
Good to 'see' you guys again! :)

**Comment by demeesterdev** [comment]
lets agree to disagree, As soon as I saw this repo i couldn't not goof around a bit ;-). but in case nice to see you around as well @JelleGraaf.

ill close the issue as i think it is resolved ;-)
